abahmed/kwatch

.github/workflows/check.yaml
.github/workflows/publish.yaml
README.md

fix workflows

---

CONTRIBUTING.md
README.md
client/client.go
config.yaml
constant/constant.go
controller/controller.go
deploy/config.yaml
event/event.go
provider/slack.go
util/util.go

- detects new pod crashes
- adds maxRecentLogLines
- adds Contributing.md
- adds comments on exported methods
- updates slack messages

feature: detect new pod crashes

---

config.yaml
controller/controller.go
go.mod
go.sum
provider/discord.go
provider/provider.go
provider/slack.go

- Adding Discord provider to the list of providers.
- Moving the constants list to be across all providers.

feature: Adding discord provider

---

.github/workflows/publish.yaml
Dockerfile
README.md
config.yaml
constant/constant.go
controller/controller.go
controller/start.go
deploy/config.yaml
go.mod
main.go
provider/discord.go
provider/slack.go
util/util.go

- support versioning
- fix conflicts

Support versioning

---

.github/workflows/publish.yaml
Dockerfile
README.md

release v0.0.6

---

README.md

release v0.0.7

---

README.md
controller/controller.go
deploy/deploy.yaml
util/util.go

Fixes # .
- welcome msg version
-grouped redundant code in utilities 
-update readme

fix: welcome msg version 

---

README.md
config.yaml
controller/controller.go
deploy/config.yaml
deploy/deploy.yaml
util/util.go

Fixes #8 .
-add the ability to choose a certain namespaces to hear from.

🎉 feature: select namespaces you want to hear from

---

README.md
deploy/deploy.yaml

release v0.1.0

---

provider/pagerduty.go

fix: escape JSON breaking characters in PagerDuty request body

---

constant/constant.go
controller/controller.go
go.mod
go.sum
main.go
upgrader/upgrader.go

feature: notify periodically on new version updates

---

README.md
config.yaml
deploy/config.yaml
provider/teams.go
storage/storage.go
util/util.go

Fixes #30  .
- Supporting Microsoft teams 
-
-

feature: support teams as a provider

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
deploy/deploy.yaml
provider/teams.go
provider/telegram.go

:tada: release v0.2.0

---

provider/teams.go

The JSON payload posted to [Teams Webhook API](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook) throws 400 bad request because the payload being sent from the provider is not properly JSON serialized. The current method (as shown below):
```go
reqBody := fmt.Sprintf(`{
"title": "%s",
"text": "%s",
}`, title, msg)
```
works fine for few cases, but it doesn't cover cases where the log message collected from the Pod's container consists of some unsafe characters. This can spoil the manual serialization being done in the above snippet and introduces a string representation which is not a valid JSON encoded text. The following fix uses proper json marshalling to fix that issue using Golang's `encoding/json` package, which takes care …

Fix: Microsoft Teams incoming webhook API throws 400 (bad request) due to malformed JSON POST payload caused by illegal escape characters

---

deploy/config.yaml
util/util_test.go

♻️ add tests for rocket chat

---

README.md
controller/controller.go
deploy/deploy.yaml

🎉 release v0.3.0

---

deploy/chart/.helmignore
deploy/chart/Chart.yaml
deploy/chart/templates/_helpers.tpl
deploy/chart/templates/configmap.yaml
deploy/chart/templates/deployment.yaml
deploy/chart/templates/rbac.yaml
deploy/chart/templates/serviceaccount.yaml
deploy/chart/values.yaml

add Helm chart.
- add helm chart

add(Helm):

---

README.md
controller/controller.go
controller/start.go
main.go

Allows to filter by reasons. e.g. in my company we only want to alert on OOMKills

Allow filtering by reasons

---

README.md
deploy/chart/Chart.yaml
deploy/deploy.yaml

🎉 release v0.6.0

---

README.md
deploy/chart/Chart.yaml
deploy/deploy.yaml

🎉 release v0.6.1

---

go.mod
go.sum
util/util.go

- fix issues of supporting email pr

fix issues of supporting email PR

---

client/client.go
constant/constant.go
controller/controller.go
main.go
provider/discord.go
provider/email.go
provider/mattermost.go
provider/opsgenie.go
provider/rocketchat.go
provider/slack.go
provider/teams.go
provider/telegram.go
util/util.go
util/util_test.go

- Fixes build and max characters per line

fix build and max characters per line

---

README.md
alertmanager/alertmanager.go
alertmanager/dingtalk/dingtalk.go
alertmanager/dingtalk/dingtalk_test.go
alertmanager/matrix/matrix.go
alertmanager/mattermost/mattermost.go
alertmanager/opsgenie/opsgenie.go
alertmanager/pagerduty/pagerduty.go
alertmanager/rocketchat/rocketchat.go
alertmanager/teams/teams.go
alertmanager/telegram/telegram.go
main.go

🚀 Support DingTalk

---

alertmanager/rocketchat/rocketchat.go
alertmanager/teams/teams.go
main.go

Fixes #52 
- Fix markdown issues in MS Teams and RocketChat

🐛 Fix markdown issues in MS Teams and RocketChat

---

Dockerfile
constant/constant.go
controller/controller.go
main.go
upgrader/upgrader.go
version/version.go

🚀 Split version in package

---

README.md
deploy/chart/Chart.yaml
deploy/deploy.yaml

🎉 release v0.7.0

---

util/util.go
util/util_test.go

♻️ Add tests to util

---

alertmanager/dingtalk/dingtalk.go
alertmanager/feishu/feishu.go
alertmanager/feishu/feishu_test.go
alertmanager/matrix/matrix.go
alertmanager/rocketchat/rocketchat.go
alertmanager/slack/slack.go
alertmanager/teams/teams.go
event/format.go

Fixes #186
- Support event html and markdown formatting
- Fix reading slack title and text from config

Support event html and markdown formatting

---

README.md
deploy/chart/.helmignore
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/chart/templates/_helpers.tpl
deploy/chart/templates/configmap.yaml
deploy/chart/templates/deployment.yaml
deploy/chart/templates/rbac.yaml
deploy/chart/templates/serviceaccount.yaml
deploy/chart/values.yaml

- Update helm chart
- Fix current issues in chart
- Add chart to README

♻️ Update helm chart

---

.github/workflows/check.yml
.github/workflows/publish.yml
Dockerfile
README.md
deploy/chart/.helmignore
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/chart/templates/_helpers.tpl
deploy/chart/templates/configmap.yaml
deploy/chart/templates/deployment.yaml
deploy/chart/templates/rbac.yaml
deploy/chart/templates/serviceaccount.yaml
deploy/chart/values.yaml

Fixes #127 
- Support Multi Arch docker (linux/amd64, linux/arm64 ,linux/arm/v6, linux/arm/v7) images

🚀 Support Multi Arch docker images

---

README.md
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/deploy.yaml

🚀 release v0.8.1

---

README.md
alertmanager/alertmanager.go
alertmanager/alertmanager_test.go
alertmanager/dingtalk/dingtalk.go
alertmanager/discord/discord.go
alertmanager/email/email.go
alertmanager/feishu/feishu.go
alertmanager/feishu/feishu_test.go
alertmanager/matrix/matrix.go
alertmanager/mattermost/mattermost.go
alertmanager/opsgenie/opsgenie.go
alertmanager/pagerduty/pagerduty.go
alertmanager/rocketchat/rocketchat.go
alertmanager/slack/slack.go
alertmanager/teams/teams.go
alertmanager/telegram/telegram.go
alertmanager/webhook/webhook.go
alertmanager/webhook/webhook_test.go
deploy/chart/templates/rbac.yaml
deploy/deploy.yaml
event/format.go

Fixes #203 #204
- use type assertions for strings in alerts
- fix teams messaging

🐛  use type assertions for strings in alerts

---

README.md
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/deploy.yaml

🎉 release v0.8.2

---

pvcmonitor/checkUsage.go
pvcmonitor/pvc.go

🐛 initialize notifiedPvc map

---

alertmanager/webhook/webhook.go

Fixes # .
- Added check if username and password are present before adding auth to request
-
-

added check before setting basic auth

---

README.md

- Add join the waitlist to readme

Add join waitlist to readme

---

.github/workflows/check.yml
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/deploy.yaml
go.mod
go.sum

🎉 release v0.8.4

---

.github/workflows/check.yml
go.mod
util/util_test.go

⬆ upgrade to go 1.22

---

alertmanager/webhook/webhook_test.go
config/config_test.go

♻️ improve test coverage

---

README.md
config/config.go
config/defaultConfig.go
main.go

Fixes #301 
- support setting custom log formatter using config

🚀 support setting custom log formatter using config

---

README.md
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/deploy.yaml

🎉 release v0.9.0

---

README.md
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/deploy.yaml

🎉 release v0.9.1

---

README.md
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/deploy.yaml

🎉 release v0.9.2

---

README.md
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/deploy.yaml

🎉 release v0.9.3

---

README.md
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/deploy.yaml

🎉 release v0.9.4

---

filter/podStatusFilter.go

- 🐛 update log message in handing pod reason

🐛 update log message in handing pod reason

---

README.md
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/deploy.yaml

🎉 release v0.9.5

---

deploy/chart/templates/deployment.yaml
deploy/chart/values.yaml

1. adds support for setting podLabels
2. adds missing podAnnotations from values

add support for podlabels

---

util/util.go

Fixes # .
- minor typo addressed
- added description to the method missing it
NOTE: Was checking the docs in https://pkg.go.dev/github.com/abahmed/kwatch@v0.10.2/util saw a typo and missing description.

fix: removed extra slash and added missing description

---

README.md
deploy/chart/Chart.yaml
deploy/chart/README.md
deploy/deploy.yaml

🎉 release v0.10.3
